version: "3.4"

services:
  api:
    build:
      context: "../"
      dockerfile: "deploy/Dockerfile"
    ports:
      - "5000:5000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"